const koa = require('koa');
const app = new koa();
const path = require('path');
const serve = require('koa-static');
const httpPort = 3000;
const main = serve(path.join(__dirname));
console.log('正在代理文件：' + path.join(__dirname));
console.log('正在监听端口：' + httpPort);
app.use(main);
app.listen(httpPort);